include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "**/generated_plugin_registrant.dart"
    - "**/build/**"
    - "**/generated_*.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/l10n*.dart"
    - "**/*.gen.dart"

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    prefer_const_constructors: true
    # IDE works bad with relative import
    # See: https://github.com/dart-lang/sdk/issues/32916
    prefer_relative_imports: false
    always_use_package_imports: true
